# Generated by Django 4.2.5 on 2023-09-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.FloatField(default=None),
        ),
    ]
