# Generated by Django 4.2.5 on 2023-09-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_box_area_box_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
