# Generated by Django 4.2.5 on 2023-09-12 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_box_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='creator',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
